GET http://localhost:9999/api/v1/task
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI5MTUxMTksInVzZXJJZCI6MTAwfQ.NviPiPdh1-d0yHaA_hPjHpOrArCPzIMqxbCnik8KAls
###
GET http://localhost:9999/api/v1/task/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4OTM1OTQsInVzZXJJZCI6MTAwfQ.ixzhpgrR7LK_a8HcOWazwIMeufU1xk4icA6jk-9ORaA

###
POST http://localhost:9999/api/v1/task
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI5MDA1NTAsInVzZXJJZCI6MTAwfQ.aI7ak38N9UhcceZp2Rog00FMZwGn6RwQU8ECQzjpPsY

{
  "description": "task description 444",
  "date": "2019-01-01T00:00:00Z",
  "labelIds": [1, 2 ]
}


###
PUT http://localhost:9999/api/v1/task/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4OTM0MzAsInVzZXJJZCI6MTAwfQ.XzCPToTbUSA2mM1xcJynnizH87r5BuR36ILeQ3qOQEA
{
  "description": "TArea actualizada",
  "date": "2019-01-01T00:00:00Z"
}

###
DELETE http://localhost:9999/api/v1/task/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI5MDA1NTAsInVzZXJJZCI6MTAwfQ.aI7ak38N9UhcceZp2Rog00FMZwGn6RwQU8ECQzjpPsY